# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17890a3ce76b642535a14a253b5e5b61937f4e40b8be3ad119583f9c727975b5aafd0a71fe8d03d20a0c5d4d672dc7a3b16d87fd0f5417fc9f69faa43fc600c4

test:
  secret_key_base: 94c572cd34e38e479980ff898479cf22f824d17d8917c25b43dd78b58064acab0cc3ec54f148403682a2a1f566522007f7a1e27bdb6899a55cf2c29fb69fa06b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
